config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard" => "users#dashboard", as: :dashboard

  resources :session_participants
  resources :user_books
  resources :questions
  resources :books
  resources :comments
  resources :group_sessions
  resources :users 
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  authenticated :user do
    # TODO: maybe change to "dashboard#index"
    root "group_sessions#index", as: :authenticated_root
  end
  
  unauthenticated :user do
    root "articles#index", as: :unauthenticated_root
  end
end

app/models/session_participant.rb
# == Schema Information
#
# Table name: session_participants
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  group_id   :integer
#  user_id    :integer
#
class SessionParticipant < ApplicationRecord
  belongs_to :user, required: true, class_name: "User", foreign_key: "user_id"

  belongs_to :group, required: true, class_name: "GroupSession", foreign_key: "group_id"

  has_many  :comments, class_name: "Comment", foreign_key: "participant_id", dependent: :destroy

  has_many  :questions, class_name: "Question", foreign_key: "participant_id", dependent: :destroy 
  
end

app/controllers/session_participants_controller.rb
class SessionParticipantsController < ApplicationController
  before_action :set_session_participant, only: %i[ show edit update destroy ]

  # GET /session_participants or /session_participants.json
  def index
    @session_participants = SessionParticipant.all
  end

  # GET /session_participants/1 or /session_participants/1.json
  def show
  end

  # GET /session_participants/new
  def new
    @session_participant = SessionParticipant.new
  end

  # GET /session_participants/1/edit
  def edit
  end

  # POST /session_participants or /session_participants.json
  def create
    @session_participant = SessionParticipant.new(session_participant_params)

    respond_to do |format|
      if @session_participant.save
        format.html { redirect_to session_participant_url(@session_participant), notice: "Session participant was successfully created." }
        format.json { render :show, status: :created, location: @session_participant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @session_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /session_participants/1 or /session_participants/1.json
  def update
    respond_to do |format|
      if @session_participant.update(session_participant_params)
        format.html { redirect_to session_participant_url(@session_participant), notice: "Session participant was successfully updated." }
        format.json { render :show, status: :ok, location: @session_participant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @session_participant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /session_participants/1 or /session_participants/1.json
  def destroy
    @session_participant.destroy

    respond_to do |format|
      format.html { redirect_to session_participants_url, notice: "Session participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_session_participant
      @session_participant = SessionParticipant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def session_participant_params
      params.require(:session_participant).permit(:user_id, :group_id)
    end
end

app/views/session_participants/_form.html.erb
<%= form_with(model: session_participant) do |form| %>
  <% if session_participant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(session_participant.errors.count, "error") %> prohibited this session_participant from being saved:</h2>

      <ul>
        <% session_participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.number_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/session_participants/_session_participant.html.erb
<div id="<%= dom_id session_participant %>">
  <p>
    <strong>User:</strong>
    <%= session_participant.user_id %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= session_participant.group_id %>
  </p>

</div>

app/views/session_participants/edit.html.erb
<h1>Editing session participant</h1>

<%= render "form", session_participant: @session_participant %>

<br>

<div>
  <%= link_to "Show this session participant", @session_participant %> |
  <%= link_to "Back to session participants", session_participants_path %>
</div>

app/views/session_participants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Session participants</h1>

<div id="session_participants">
  <% @session_participants.each do |session_participant| %>
    <%= render session_participant %>
    <p>
      <%= link_to "Show this session participant", session_participant %>
    </p>
  <% end %>
</div>

<%= link_to "New session participant", new_session_participant_path %>

app/views/session_participants/new.html.erb
<h1>New session participant</h1>

<%= render "form", session_participant: @session_participant %>

<br>

<div>
  <%= link_to "Back to session participants", session_participants_path %>
</div>

app/views/session_participants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @session_participant %>

<div>
  <%= link_to "Edit this session participant", edit_session_participant_path(@session_participant) %> |
  <%= link_to "Back to session participants", session_participants_path %>

  <%= button_to "Destroy this session participant", @session_participant, method: :delete %>
</div>