config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard" => "users#dashboard", as: :dashboard

  resources :session_participants
  resources :user_books
  resources :questions
  resources :books
  resources :comments
  resources :group_sessions
  resources :users 
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  authenticated :user do
    # TODO: maybe change to "dashboard#index"
    root "group_sessions#index", as: :authenticated_root
  end
  
  unauthenticated :user do
    root "articles#index", as: :unauthenticated_root
  end
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id             :integer          not null, primary key
#  body           :string           not null
#  dislikes       :integer
#  likes          :integer          default(0), not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  participant_id :integer
#  question_id    :integer
#
class Comment < ApplicationRecord
  belongs_to :question, class_name: "Question", foreign_key: "question_id", dependent: :destroy
  belongs_to :participant, required: true, class_name: "SessionParticipant", foreign_key: "participant_id" 
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:body, :likes, :dislikes, :question_id, :participant_id)
    end
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= comment.likes %>
  </p>

  <p>
    <strong>Dislikes:</strong>
    <%= comment.dislikes %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= comment.question_id %>
  </p>

  <p>
    <strong>Participant:</strong>
    <%= comment.participant_id %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.text_field :likes %>
  </div>

  <div>
    <%= form.label :dislikes, style: "display: block" %>
    <%= form.number_field :dislikes %>
  </div>

  <div>
    <%= form.label :question_id, style: "display: block" %>
    <%= form.number_field :question_id %>
  </div>

  <div>
    <%= form.label :participant_id, style: "display: block" %>
    <%= form.number_field :participant_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>