config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard" => "users#dashboard", as: :dashboard

  resources :session_participants
  resources :user_books
  resources :questions
  resources :books
  resources :comments
  resources :group_sessions
  resources :users 
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  authenticated :user do
    # TODO: maybe change to "dashboard#index"
    root "group_sessions#index", as: :authenticated_root
  end
  
  unauthenticated :user do
    root "articles#index", as: :unauthenticated_root
  end
end

app/models/group_session.rb
# == Schema Information
#
# Table name: group_sessions
#
#  id              :integer          not null, primary key
#  list_of_members :string
#  name_of_group   :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  book_id         :integer
#  owner_id        :integer
#
class GroupSession < ApplicationRecord
  
  belongs_to :user, required: true, class_name: "User", foreign_key: "user_id"

  has_many  :group_sessions, class_name: "GroupSession", foreign_key: "book_id", dependent: :destroy

  has_many  :user_books, class_name: "UserBook", foreign_key: "book_id", dependent: :destroy 
end

app/controllers/group_sessions_controller.rb
class GroupSessionsController < ApplicationController
  before_action :set_group_session, only: %i[ show edit update destroy ]

  # GET /group_sessions or /group_sessions.json
  def index
    @group_sessions = GroupSession.all
  end

  # GET /group_sessions/1 or /group_sessions/1.json
  def show
  end

  # GET /group_sessions/new
  def new
    @group_session = GroupSession.new
  end

  # GET /group_sessions/1/edit
  def edit
  end

  # POST /group_sessions or /group_sessions.json
  def create
    @group_session = GroupSession.new(group_session_params)

    respond_to do |format|
      if @group_session.save
        format.html { redirect_to group_session_url(@group_session), notice: "Group session was successfully created." }
        format.json { render :show, status: :created, location: @group_session }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /group_sessions/1 or /group_sessions/1.json
  def update
    respond_to do |format|
      if @group_session.update(group_session_params)
        format.html { redirect_to group_session_url(@group_session), notice: "Group session was successfully updated." }
        format.json { render :show, status: :ok, location: @group_session }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group_session.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /group_sessions/1 or /group_sessions/1.json
  def destroy
    @group_session.destroy

    respond_to do |format|
      format.html { redirect_to group_sessions_url, notice: "Group session was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_session
      @group_session = GroupSession.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def group_session_params
      params.require(:group_session).permit(:owner_id, :book_id, :name_of_group, :list_of_members)
    end
end

app/views/group_sessions/_form.html.erb
<%= form_with(model: group_session) do |form| %>
  <% if group_session.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group_session.errors.count, "error") %> prohibited this group_session from being saved:</h2>

      <ul>
        <% group_session.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :owner_id, style: "display: block" %>
    <%= form.number_field :owner_id %>
  </div>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.number_field :book_id %>
  </div>

  <div>
    <%= form.label :name_of_group, style: "display: block" %>
    <%= form.text_field :name_of_group %>
  </div>

  <div>
    <%= form.label :list_of_members, style: "display: block" %>
    <%= form.text_field :list_of_members %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/group_sessions/_group_session.html.erb
<div id="<%= dom_id group_session %>">
  <p>
    <strong>Owner:</strong>
    <%= group_session.owner_id %>
  </p>

  <p>
    <strong>Book:</strong>
    <%= group_session.book_id %>
  </p>

  <p>
    <strong>Name of group:</strong>
    <%= group_session.name_of_group %>
  </p>

  <p>
    <strong>List of members:</strong>
    <%= group_session.list_of_members %>
  </p>

</div>

app/views/group_sessions/edit.html.erb
<h1>Editing group session</h1>

<%= render "form", group_session: @group_session %>

<br>

<div>
  <%= link_to "Show this group session", @group_session %> |
  <%= link_to "Back to group sessions", group_sessions_path %>
</div>

app/views/group_sessions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Welcome User </h1>

<div id="group_sessions">
  <% @group_sessions.each do |group_session| %>
    <%= render group_session %>
    <p>
      <%= link_to "Show this group session", group_session %>
    </p>
  <% end %>
</div>

<%= link_to "New group session", new_group_session_path %>

app/views/group_sessions/new.html.erb
<h1>New group session</h1>

<%= render "form", group_session: @group_session %>

<br>

<div>
  <%= link_to "Back to group sessions", group_sessions_path %>
</div>

app/views/group_sessions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group_session %>

<div>
  <%= link_to "Edit this group session", edit_group_session_path(@group_session) %> |
  <%= link_to "Back to group sessions", group_sessions_path %>

  <%= button_to "Destroy this group session", @group_session, method: :delete %>
</div>