config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get "/dashboard" => "users#dashboard", as: :dashboard

  resources :session_participants
  resources :user_books
  resources :questions
  resources :books
  resources :comments
  resources :group_sessions
  resources :users 
  

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")

  authenticated :user do
    # TODO: maybe change to "dashboard#index"
    root "group_sessions#index", as: :authenticated_root
  end
  
  unauthenticated :user do
    root "articles#index", as: :unauthenticated_root
  end
end

app/models/user_book.rb
# == Schema Information
#
# Table name: user_books
#
#  id         :integer          not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  book_id    :integer
#  user_id    :integer
#
class UserBook < ApplicationRecord
  belongs_to :user, required: true, class_name: "User", foreign_key: "user_id"

  belongs_to :book, required: true, class_name: "Book", foreign_key: "book_id"
  
end

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController
  before_action :set_user_book, only: %i[ show edit update destroy ]

  # GET /user_books or /user_books.json
  def index
    @user_books = UserBook.all
  end

  # GET /user_books/1 or /user_books/1.json
  def show
  end

  # GET /user_books/new
  def new
    @user_book = UserBook.new
  end

  # GET /user_books/1/edit
  def edit
  end

  # POST /user_books or /user_books.json
  def create
    @user_book = UserBook.new(user_book_params)

    respond_to do |format|
      if @user_book.save
        format.html { redirect_to user_book_url(@user_book), notice: "User book was successfully created." }
        format.json { render :show, status: :created, location: @user_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_books/1 or /user_books/1.json
  def update
    respond_to do |format|
      if @user_book.update(user_book_params)
        format.html { redirect_to user_book_url(@user_book), notice: "User book was successfully updated." }
        format.json { render :show, status: :ok, location: @user_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_books/1 or /user_books/1.json
  def destroy
    @user_book.destroy

    respond_to do |format|
      format.html { redirect_to user_books_url, notice: "User book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_book
      @user_book = UserBook.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_book_params
      params.require(:user_book).permit(:book_id, :user_id)
    end
end

app/views/user_books/_form.html.erb
<%= form_with(model: user_book) do |form| %>
  <% if user_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user_book.errors.count, "error") %> prohibited this user_book from being saved:</h2>

      <ul>
        <% user_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :book_id, style: "display: block" %>
    <%= form.number_field :book_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/user_books/_user_book.html.erb
<div id="<%= dom_id user_book %>">
  <p>
    <strong>Book:</strong>
    <%= user_book.book_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%= user_book.user_id %>
  </p>

</div>

app/views/user_books/edit.html.erb
<h1>Editing user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Show this user book", @user_book %> |
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>User books</h1>

<div id="user_books">
  <% @user_books.each do |user_book| %>
    <%= render user_book %>
    <p>
      <%= link_to "Show this user book", user_book %>
    </p>
  <% end %>
</div>

<%= link_to "New user book", new_user_book_path %>

app/views/user_books/new.html.erb
<h1>New user book</h1>

<%= render "form", user_book: @user_book %>

<br>

<div>
  <%= link_to "Back to user books", user_books_path %>
</div>

app/views/user_books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user_book %>

<div>
  <%= link_to "Edit this user book", edit_user_book_path(@user_book) %> |
  <%= link_to "Back to user books", user_books_path %>

  <%= button_to "Destroy this user book", @user_book, method: :delete %>
</div>